name: Build packages
on:
  push:

jobs:
  build-packages:
    runs-on: ubuntu-latest
    name: Build packages

    steps:
      - name : Checkout
        uses: actions/checkout@v2

      - name: Setup NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Build no-pinia version
        working-directory: ./vue-skeleton-no-pinia
        run: npm install && npm run build

      - name: Build pinia version
        working-directory: ./vue-skeleton-with-pinia
        run: npm install && npm run build

      - name: Compare file sizes
        run: |
          echo '```' >> $GITHUB_STEP_SUMMARY
          ls -lh */dist/assets/index.*.js | tee -a $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
